version: '2.1'

services:
  ldapdb:
    build:
      context: .
      dockerfile: Dockerfile.ldap_phpldapadmin
    image: ua2web/ldap:2.4.47
    env_file:
      - api.env

  mercurial:
    build:
      context: .
      dockerfile: Dockerfile.mercurial
    image: ua2web/mercurial:1.12.2
    env_file:
      - api.env
    ports:
      - "80:80"
